name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
          # Commented out other platforms to reduce build time - uncomment as needed
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows # Build a Windows standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Free disk space on all platforms
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/cache@v3
        with:
          path: Library/Bee
          key: Library-${{ matrix.targetPlatform }}-minimal
          restore-keys: Library-${{ matrix.targetPlatform }}-minimal

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: '-nographics -disable-gpu'

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: 3

  deployToGitHubPages:
    name: Deploy WebGL to GitHub Pages
    runs-on: ubuntu-latest
    needs: buildForAllSupportedPlatforms
    # Only run on pushes to main or manual workflow runs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download WebGL Build
        uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: webgl-build

      # Create index.html if it doesn't exist
      - name: Ensure index.html exists
        run: |
          if [ ! -f webgl-build/index.html ]; then
            echo "Creating a redirect index.html file"
            MAIN_HTML=$(find webgl-build -name "*.html" | head -n 1)
            if [ -n "$MAIN_HTML" ]; then
              MAIN_HTML_RELATIVE=$(echo $MAIN_HTML | sed 's|webgl-build/||')
              echo "<meta http-equiv=\"refresh\" content=\"0; url=./${MAIN_HTML_RELATIVE}\">" > webgl-build/index.html
            else
              echo "<h1>Unity WebGL Build</h1><p>WebGL build coming soon.</p>" > webgl-build/index.html
            fi
          fi

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'webgl-build'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
